name: "Terraform Actions"

on:
  push:
    branches:
      - development

env:
  TF_INPUT: true
  TF_IN_AUTOMATION: true
  TF_LOG: INFO

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: format
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        if: (success() || failure())
        run: terraform validate
